# Caelestia Shell global shortcuts (DBus)
bind = SUPER, D, global, caelestia:launcher
bind = SUPER, Tab, global, caelestia:dashboard
bind = SUPER, Escape, global, caelestia:session
bind = SUPER, N, global, caelestia:nexus
bind = SUPER, S, global, caelestia:sidebar
bind = SUPER, U, global, caelestia:utilities
bind = SUPER SHIFT, D, global, caelestia:showall

# Super alone - tap to toggle launcher
bind = , SUPER_L, global, caelestia:launcher

# Lock screen
bind = SUPER, L, exec, loginctl lock-session
