
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- Autogenerated config customized by Maple

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- eDP-1: laptop screen (primary)
hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1.0 })
-- HDMI-A-1: mirror laptop screen
hl.monitor({ output = "HDMI-A-1", mode = "preferred", position = "auto", scale = 1.0, mirror = "eDP-1" })
-- Disable DPMS - no screen blanking
hl.on("hyprland.start", function ()
  hl.exec_cmd('hyprctl keyword monitor ",dpms,off"')
end)


----------------------
---- HYPRSPLIT ------
----------------------
-- Workspaces 1-10 100% INDEPENDIENTES por monitor (libreria lua hyprsplit).
-- eDP-1 -> IDs reales 1-10, HDMI-A-1 -> IDs reales 11-20. Los binds SUPER+N
-- actuan sobre la monitor ACTUAL (sin saltar al otro monitor).
-- Los workspaces se renombran al ordinal (1-9 y "0" para el 10) para que el bar
-- de Caelestia muestre 1-10 identicos en ambos monitores (el 10 se ve como "0",
-- convencion de Hyprland: SUPER+0 = workspace 10).
package.path = os.getenv("HOME") .. "/.config/hypr/?.lua;" .. os.getenv("HOME") .. "/.config/hypr/?/init.lua;" .. package.path

local hs = require("hyprsplit")
hs.config({ num_workspaces = 10, persistent_workspaces = true })
hs.monitor_priority({ "eDP-1", "HDMI-A-1" })

local function hyprsplit_ordinal(ws_id)
    local nws = hs.get_config("num_workspaces") or 10
    return ((ws_id - 1) % nws) + 1
end

local function hyprsplit_rename(ws)
    if not ws or ws.special then
        return
    end
    local ordinal = hyprsplit_ordinal(ws.id)
    local name = tostring(ordinal == 10 and 0 or ordinal)
    if ws.name ~= name then
        hl.dispatch(hl.dsp.workspace.rename({ workspace = ws.id, name = name }))
    end
end

-- GLOBAL a proposito: el re-renombrado diferido (exec_cmd -> hyprctl eval) la invoca
function hyprsplit_rename_all()
    for _, ws in ipairs(hl.get_workspaces()) do
        hyprsplit_rename(ws)
    end
end

-- Los eventos hl.on (workspace.created, active, change...) NO disparan de forma
-- fiable en esta build 0.56.2-Maple, asi que el renombrado a ordinal se ejecuta
-- tras cada bind de workspace (wrapper) y en config.reloaded / hyprland.start.
-- Los workspaces persistentes pueden materializar DESPUES de estos handlers, por
-- eso se re-lanza el renombrado 1.2s mas tarde via hyprctl eval.
local function hyprsplit_rename_soon()
    hl.exec_cmd([[sh -c 'sleep 1.2; hyprctl eval "hyprsplit_rename_all()"']])
end

local function hyprsplit_wrap(dispatch_fun)
    return function()
        dispatch_fun()
        hyprsplit_rename_all()
    end
end

hl.on("config.reloaded", function()
    hyprsplit_rename_all()
    hyprsplit_rename_soon()
end)
hl.on("hyprland.start", function()
    hyprsplit_rename_all()
    hyprsplit_rename_soon()
end)


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "tilix"
local fileManager = "thunar"
local menu        = "hyprlauncher"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
hl.on("hyprland.start", function ()
  hl.exec_cmd("caelestia shell -d")
  -- daemon de GPU Screen Recorder: REQUERIDO para que Alt+F9 (gsr-toggle) funcione,
  -- ya que Hyprland NO procesa los .desktop de ~/.config/autostart.
  hl.exec_cmd("gsr-ui launch-daemon")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

---- FONT RENDERING (scale 0.8, 1080p 15.6 inch) ----
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

---- NVIDIA GPU (default for all apps, Hyprland stays on Intel) ----
hl.env("__NV_PRIME_RENDER_OFFLOAD", "1")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("__VK_LAYER_NV_optimus", "NVIDIA_only")
hl.env("LIBVA_DRIVER_NAME", "nvidia")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 0,
        gaps_out = 0,

        border_size = 1,

        col = {
            active_border   = "rgba(00000000)",
            inactive_border = "rgba(00000000)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = true,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },

        screen_shader = os.getenv("HOME") .. "/.config/hypr/shaders/saturation.glsl",
    },

    animations = {
        enabled = true,
    },

    misc = {
        render_unfocused_fps = 0,
        vrr = 0,
        mouse_move_enables_dpms = false,
        key_press_enables_dpms = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 1,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 1,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us,latam",
        kb_variant = "intl,",
        kb_model   = "",
        kb_options = "grp:win_space_toggle",
        kb_rules   = "",

        follow_mouse = 1,

        -- Configuración de puntero: NEUTRA y GLOBAL para todos los mouse.
        -- sensitivity 0 = sin modificación (1:1). accel_profile "flat" =
        -- sin aceleración (curva plana) → también quita el retardo de la
        -- aceleración, entrada a mínima latencia. Aplica a mouse y touchpad.
        sensitivity   = 0, -- -1.0 - 1.0, 0 = neutro
        accel_profile = "flat",

        touchpad = {
            natural_scroll = false,
        },
    },
})

-- (sin per-device: la config de puntero es global y neutra para todos)

-- hl.gesture({  -- commented: already defined by default
--     fingers = 3,
--     direction = "horizontal",
--     action = "workspace"
-- })

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
-- (eliminado: la config de puntero es global y neutra — sin overrides por device)


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind("ALT + F4", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

hl.bind(mainMod .. " + D",       hl.dsp.exec_cmd("qs -c caelestia ipc call drawers toggle launcher"))
hl.bind(mainMod .. " + Tab",     hl.dsp.exec_cmd("qs -c caelestia ipc call drawers toggle dashboard"))
hl.bind(mainMod .. " + Escape",  hl.dsp.exec_cmd("qs -c caelestia ipc call drawers toggle session"))
hl.bind(mainMod .. " + N",       hl.dsp.exec_cmd("qs -c caelestia ipc call drawers toggle nexus"))
hl.bind(mainMod .. " + S",       hl.dsp.exec_cmd("qs -c caelestia ipc call drawers toggle sidebar"))
hl.bind(mainMod .. " + U",       hl.dsp.exec_cmd("qs -c caelestia ipc call drawers toggle utilities"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("qs -c caelestia ipc call drawers toggle showall"))

-- Screenshot & Screen Recording
hl.bind("Print",             hl.dsp.exec_cmd("screenshot"),        { locked = true })
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("screenshot --area"), { locked = true })
hl.bind("SHIFT + Print",     hl.dsp.exec_cmd("screenshot --area"), { locked = true })
hl.bind("ALT + F9",          hl.dsp.exec_cmd("gsr-toggle"),        { locked = true })
hl.bind("ALT + Z",           hl.dsp.exec_cmd("gsr-ui"),            { locked = true })

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Move active window to the other monitor with mainMod + SHIFT + arrows
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ monitor = "HDMI-A-1" }))
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ monitor = "eDP-1" }))

-- Switch workspaces 1-10 en la monitor ACTUAL (100% independientes, hyprsplit)
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hyprsplit_wrap(hs.dsp.focus({ workspace = i })))
    hl.bind(mainMod .. " + SHIFT + " .. key, hyprsplit_wrap(hs.dsp.window.move({ workspace = i, follow = true })))
end

-- Super+S moved to Caelestia sidebar (line ~275)
-- hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
-- hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces (per monitor, excluyendo vacios) with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hyprsplit_wrap(hs.dsp.focus({ workspace = "e+1" })))
hl.bind(mainMod .. " + mouse_up",   hyprsplit_wrap(hs.dsp.focus({ workspace = "e-1" })))

-- Rescatar ventanas "perdidas" (p.ej. al desenchufar un monitor) con SUPER + G
hl.bind(mainMod .. " + G", hyprsplit_wrap(hs.dsp.grab_rogue_windows()))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Tilix: blur + transparencia
hl.window_rule({
    name  = "tilix-blur",
    match = { class = "com.gexperts.Tilix" },
    opacity = 0.85,
})

-- Minecraft Bedrock: tearing inmediato para eliminar latencia de presentacion
hl.window_rule({
    name      = "minecraft-tearing",
    match     = { class = "^minecraft.windows.exe$" },
    immediate = true,
})
